#*******************************************************************************
#
#  Copyright 2011 Drakenclimber, LLC.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#*******************************************************************************
# Revision information.  DO NOT MODIFY.  This is auto-generated by the SCM.
#
# $Revision: $
# $Date: $
#
#*******************************************************************************

#*******************************************************************************
#
#  Please sort the libraries and sources files alphabetically.
#
#*******************************************************************************

#*******************************************************************************
#  RTOS
#*******************************************************************************
ifeq ($(RTOS), CHIBIOS)
    INC_PATHS +=                                                               \
        rtos/chibios/boards/simulator                                          \
        rtos/chibios/os/hal/include                                            \
        rtos/chibios/os/kernel/include                                         \
        rtos/chibios/os/ports/GCC/SIMIA32                                      \
        rtos/chibios/os/various                                                \
        rtos/chibios/test

    ifeq ($(ENVIRONMENT), LINUX)
        INC_PATHS +=                                                           \
            rtos/chibios/demos/Posix-GCC                                       \
            rtos/chibios/os/hal/platforms/Posix

    else ifeq ($(ENVIRONMENT), DOS)
        INC_PATHS +=                                                           \
            rtos/chibios/demos/Win32-MinGW                                     \
            rtos/chibios/os/hal/platforms/Win32

    endif

    RTOS_SRC_LIST :=                                                           \
        rtos/chibios/boards/simulator/board.o                                  \
        rtos/chibios/os/hal/src/adc.o                                          \
        rtos/chibios/os/hal/src/can.o                                          \
        rtos/chibios/os/hal/src/hal.o                                          \
        rtos/chibios/os/hal/src/mac.o                                          \
        rtos/chibios/os/hal/src/mmc_spi.o                                      \
        rtos/chibios/os/hal/src/pal.o                                          \
        rtos/chibios/os/hal/src/pwm.o                                          \
        rtos/chibios/os/hal/src/serial.o                                       \
        rtos/chibios/os/hal/src/spi.o                                          \
        rtos/chibios/os/hal/src/uart.o                                         \
        rtos/chibios/os/kernel/src/chcond.o                                    \
        rtos/chibios/os/kernel/src/chdebug.o                                   \
        rtos/chibios/os/kernel/src/chdynamic.o                                 \
        rtos/chibios/os/kernel/src/chevents.o                                  \
        rtos/chibios/os/kernel/src/chheap.o                                    \
        rtos/chibios/os/kernel/src/chlists.o                                   \
        rtos/chibios/os/kernel/src/chmboxes.o                                  \
        rtos/chibios/os/kernel/src/chmemcore.o                                 \
        rtos/chibios/os/kernel/src/chmempools.o                                \
        rtos/chibios/os/kernel/src/chmsg.o                                     \
        rtos/chibios/os/kernel/src/chmtx.o                                     \
        rtos/chibios/os/kernel/src/chqueues.o                                  \
        rtos/chibios/os/kernel/src/chregistry.o                                \
        rtos/chibios/os/kernel/src/chschd.o                                    \
        rtos/chibios/os/kernel/src/chsem.o                                     \
        rtos/chibios/os/kernel/src/chsys.o                                     \
        rtos/chibios/os/kernel/src/chthreads.o                                 \
        rtos/chibios/os/kernel/src/chvt.o                                      \
        rtos/chibios/os/ports/GCC/SIMIA32/chcore.o                             \
        rtos/chibios/os/various/shell.o                                        \
        rtos/chibios/test/test.o                                               \
        rtos/chibios/test/testbmk.o                                            \
        rtos/chibios/test/testdyn.o                                            \
        rtos/chibios/test/testevt.o                                            \
        rtos/chibios/test/testheap.o                                           \
        rtos/chibios/test/testmbox.o                                           \
        rtos/chibios/test/testmsg.o                                            \
        rtos/chibios/test/testmtx.o                                            \
        rtos/chibios/test/testpools.o                                          \
        rtos/chibios/test/testqueues.o                                         \
        rtos/chibios/test/testsem.o                                            \
        rtos/chibios/test/testthd.o

    ifeq ($(ENVIRONMENT), LINUX)
        RTOS_SRC_LIST +=                                                       \
            rtos/chibios/demos/Posix-GCC/main.o                                \
            rtos/chibios/os/hal/platforms/Posix/hal_lld.o                      \
            rtos/chibios/os/hal/platforms/Posix/pal_lld.o                      \
            rtos/chibios/os/hal/platforms/Posix/serial_lld.o

    else ifeq ($(ENVIRONMENT), DOS)
        RTOS_SRC_LIST +=                                                       \
            rtos/chibios/demos/Win32-MinGW/main.o                              \
            rtos/chibios/os/hal/platforms/Win32/hal_lld.o                      \
            rtos/chibios/os/hal/platforms/Win32/pal_lld.o                      \
            rtos/chibios/os/hal/platforms/Win32/serial_lld.o

    else
        $(call ERROR_HANDLER, "unsupported environment, $(ENVIRONMENT), for chibios RTOS")

    endif # ifeq ($(ENVIRONMENT), LINUX)
   
else
    $(call error_handler, "Unsupported RTOS.")

endif