#*******************************************************************************
#
#  Copyright 2011 Drakenclimber, LLC.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#*******************************************************************************
# Revision information.  DO NOT MODIFY.  This is auto-generated by the SCM.
#
# $Revision: $
# $Date: $
#
#*******************************************************************************

#*******************************************************************************
#  Definitions
#*******************************************************************************
EXECUTABLE := $(EXE_DIR)/$(VARIANT)

INC_PATHS +=

ARCHIVER_FLAGS +=                                                              \
   cr

ASSEMBLER_DEFINES +=

ASSEMBLER_FLAGS +=

COMPILER_DEFINES +=                                                            \
   -D_GNU_SOURCE                                                               \
   -DSHELL_USE_IPRINTF=FALSE                                                   \
   -DSIMULATOR

COMPILER_FLAGS +=                                                              \
   -c                                                                          \
   -ffloat-store                                                               \
   -fomit-frame-pointer                                                        \
   -fverbose-asm                                                               \
   -ggdb                                                                       \
   -MD                                                                         \
   -MP                                                                         \
   -O2                                                                         \
   -std=c99                                                                    \
   -Wall                                                                       \
   -Wextra                                                                     \
   -Wstrict-prototypes

LINKER_FLAGS +=                                                                \
   -lm                                                                         \
   -lpthread                                                                   \
   -o $(EXECUTABLE)                                                            \
   -Wl                                                                         \
   --cref                                                                      \
   --no-warn-mismatch

#*******************************************************************************
#  Tools
#*******************************************************************************
AR := ar             # Archiver
AS := gcc            # Assembler
CC := gcc            # C compiler
LK := gcc            # Linker

#*******************************************************************************
#  Targets
#*******************************************************************************
$(OUT_DIR)/%.o : $(SRC_DIR)/%.c
	@echo Building $(notdir $@)
	-$(call MKDIR_IF_DNE, $(dir $@))
	$(CC) $(COMPILER_FLAGS) $(COMPILER_DEFINES) -MF $(@:.o=.d) $(INC_LIST) $< -o $@ 

$(ARCHIVE_LIST): $$(addprefix $$(OUT_DIR)/, $$($$(notdir $$(patsubst %.a,%_SRC_LIST,$$@))))
	@echo Creating $(notdir $@)
	-$(call MKDIR_IF_DNE, $(dir $@))
	$(AR) $(ARCHIVER_FLAGS) $@ $^

$(EXECUTABLE): $(ARCHIVE_LIST)
	@echo Linking $(notdir $@)
	-$(call MKDIR_IF_DNE, $(dir $@))
	$(LK) $(ARCHIVE_LIST) $(LINKER_FLAGS)

toolchain_clean: ;
	@echo Deleting *.o files
	-$(foreach object_file, $(SRC_LIST), $(call DELETE_FILE, $(object_file)))
	@echo Deleting *.d files
	-$(foreach object_file, $(SRC_LIST:.o=.d), $(call DELETE_FILE, $(object_file)))
	@echo Deleting *.a files
	-$(foreach archive_file, $(ARCHIVE_LIST), $(call DELETE_FILE, $(archive_file)))
	@echo Deleting $(notdir $(EXECUTABLE))
	-$(call DELETE_FILE, $(EXECUTABLE))

toolchain_help: ;
	@echo "+-------------------------------------------------------------------+"
	@echo "| GCC help information                                              |"
	@echo "+-------------------------------------------------------------------+"
	@echo "|                                                                   |"
